# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae-Meas_Pref_0_15.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 761)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 391, 712))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 30, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 200, 281, 85))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.selFsLab = QtWidgets.QLabel(self.layoutWidget)
        self.selFsLab.setObjectName("selFsLab")
        self.gridLayout.addWidget(self.selFsLab, 0, 0, 1, 1)
        self.standardFs = QtWidgets.QCheckBox(self.layoutWidget)
        self.standardFs.setObjectName("standardFs")
        self.gridLayout.addWidget(self.standardFs, 0, 1, 3, 1)
        self.FsSel = QtWidgets.QComboBox(self.layoutWidget)
        self.FsSel.setMinimumSize(QtCore.QSize(162, 0))
        self.FsSel.setObjectName("FsSel")
        self.gridLayout.addWidget(self.FsSel, 1, 0, 1, 1)
        self.fsEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fsEdit.setObjectName("fsEdit")
        self.gridLayout.addWidget(self.fsEdit, 2, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 350, 191, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.windowLab = QtWidgets.QLabel(self.layoutWidget_2)
        self.windowLab.setObjectName("windowLab")
        self.verticalLayout_5.addWidget(self.windowLab)
        self.WindowSel = QtWidgets.QComboBox(self.layoutWidget_2)
        self.WindowSel.setMinimumSize(QtCore.QSize(162, 0))
        self.WindowSel.setObjectName("WindowSel")
        self.verticalLayout_5.addWidget(self.WindowSel)
        self.Dither = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Dither.setGeometry(QtCore.QRect(220, 170, 101, 17))
        self.Dither.setObjectName("Dither")
        self.layoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 150, 191, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bitLab = QtWidgets.QLabel(self.layoutWidget_3)
        self.bitLab.setObjectName("bitLab")
        self.verticalLayout_6.addWidget(self.bitLab)
        self.Bit_depth = QtWidgets.QComboBox(self.layoutWidget_3)
        self.Bit_depth.setMinimumSize(QtCore.QSize(162, 0))
        self.Bit_depth.setObjectName("Bit_depth")
        self.verticalLayout_6.addWidget(self.Bit_depth)
        self.overlapPercent = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.overlapPercent.setGeometry(QtCore.QRect(230, 370, 62, 22))
        self.overlapPercent.setObjectName("overlapPercent")
        self.OverlapTest = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.OverlapTest.setGeometry(QtCore.QRect(230, 340, 75, 23))
        self.OverlapTest.setObjectName("OverlapTest")
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 520, 191, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.styleSheetLab = QtWidgets.QLabel(self.layoutWidget1)
        self.styleSheetLab.setObjectName("styleSheetLab")
        self.verticalLayout.addWidget(self.styleSheetLab)
        self.styleSheetSel = QtWidgets.QComboBox(self.layoutWidget1)
        self.styleSheetSel.setMinimumSize(QtCore.QSize(162, 0))
        self.styleSheetSel.setObjectName("styleSheetSel")
        self.verticalLayout.addWidget(self.styleSheetSel)
        self.layoutWidget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget2.setGeometry(QtCore.QRect(219, 459, 191, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.defFreqMaxLab = QtWidgets.QLabel(self.layoutWidget2)
        self.defFreqMaxLab.setObjectName("defFreqMaxLab")
        self.verticalLayout_2.addWidget(self.defFreqMaxLab)
        self.defFreqMaxEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.defFreqMaxEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMaxEdit.setObjectName("defFreqMaxEdit")
        self.verticalLayout_2.addWidget(self.defFreqMaxEdit)
        self.layoutWidget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 460, 191, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.defFreqMinLab = QtWidgets.QLabel(self.layoutWidget3)
        self.defFreqMinLab.setObjectName("defFreqMinLab")
        self.verticalLayout_3.addWidget(self.defFreqMinLab)
        self.defFreqMinEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.defFreqMinEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMinEdit.setObjectName("defFreqMinEdit")
        self.verticalLayout_3.addWidget(self.defFreqMinEdit)
        self.layoutWidget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 290, 191, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buffSizeLab = QtWidgets.QLabel(self.layoutWidget4)
        self.buffSizeLab.setObjectName("buffSizeLab")
        self.verticalLayout_4.addWidget(self.buffSizeLab)
        self.buffSizeSel = QtWidgets.QComboBox(self.layoutWidget4)
        self.buffSizeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.buffSizeSel.setObjectName("buffSizeSel")
        self.verticalLayout_4.addWidget(self.buffSizeSel)
        self.layoutWidget5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 61, 281, 73))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget5)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.selInterfaceLab = QtWidgets.QLabel(self.layoutWidget5)
        self.selInterfaceLab.setObjectName("selInterfaceLab")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.selInterfaceLab)
        self.updateInterface = QtWidgets.QToolButton(self.layoutWidget5)
        self.updateInterface.setObjectName("updateInterface")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.updateInterface)
        self.InputSel = QtWidgets.QComboBox(self.layoutWidget5)
        self.InputSel.setMinimumSize(QtCore.QSize(162, 0))
        self.InputSel.setObjectName("InputSel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.InputSel)
        self.selInterfaceLab_2 = QtWidgets.QLabel(self.layoutWidget5)
        self.selInterfaceLab_2.setObjectName("selInterfaceLab_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.selInterfaceLab_2)
        self.OutputSel_2 = QtWidgets.QComboBox(self.layoutWidget5)
        self.OutputSel_2.setMinimumSize(QtCore.QSize(162, 0))
        self.OutputSel_2.setObjectName("OutputSel_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.OutputSel_2)
        self.selInterfaceLab_3 = QtWidgets.QLabel(self.layoutWidget5)
        self.selInterfaceLab_3.setObjectName("selInterfaceLab_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.selInterfaceLab_3)
        self.layoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 610, 191, 41))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_7.setMinimumSize(QtCore.QSize(162, 0))
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_7.addWidget(self.comboBox_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.updateInterface, self.InputSel)
        Dialog.setTabOrder(self.InputSel, self.OutputSel_2)
        Dialog.setTabOrder(self.OutputSel_2, self.Bit_depth)
        Dialog.setTabOrder(self.Bit_depth, self.Dither)
        Dialog.setTabOrder(self.Dither, self.FsSel)
        Dialog.setTabOrder(self.FsSel, self.standardFs)
        Dialog.setTabOrder(self.standardFs, self.fsEdit)
        Dialog.setTabOrder(self.fsEdit, self.buffSizeSel)
        Dialog.setTabOrder(self.buffSizeSel, self.WindowSel)
        Dialog.setTabOrder(self.WindowSel, self.defFreqMinEdit)
        Dialog.setTabOrder(self.defFreqMinEdit, self.defFreqMaxEdit)
        Dialog.setTabOrder(self.defFreqMaxEdit, self.styleSheetSel)
        Dialog.setTabOrder(self.styleSheetSel, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.comboBox_7)
        Dialog.setTabOrder(self.comboBox_7, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.lineEdit_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Opslag lokatie"))
        self.selFsLab.setText(_translate("Dialog", "Select Fs"))
        self.standardFs.setText(_translate("Dialog", "Standard Fs"))
        self.windowLab.setText(_translate("Dialog", "Default Window"))
        self.Dither.setText(_translate("Dialog", "dither on/off"))
        self.bitLab.setText(_translate("Dialog", "Bit Depth"))
        self.OverlapTest.setText(_translate("Dialog", "Test"))
        self.styleSheetLab.setText(_translate("Dialog", "Style Sheet"))
        self.defFreqMaxLab.setText(_translate("Dialog", "default frequency Max"))
        self.defFreqMinLab.setText(_translate("Dialog", "default frequency Min"))
        self.buffSizeLab.setText(_translate("Dialog", "buffersize"))
        self.selInterfaceLab.setText(_translate("Dialog", "select interface"))
        self.updateInterface.setText(_translate("Dialog", "Update interface"))
        self.selInterfaceLab_2.setText(_translate("Dialog", "select Input"))
        self.selInterfaceLab_3.setText(_translate("Dialog", "select Output"))
        self.label_8.setText(_translate("Dialog", "select interface"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

