# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae-Meas_Pref_0_15.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(378, 683)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 358, 630))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.fileLayout = QtWidgets.QFormLayout()
        self.fileLayout.setObjectName("fileLayout")
        self.File_loc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.File_loc.setObjectName("File_loc")
        self.fileLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.File_loc)
        self.File_loc_box1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.File_loc_box1.setObjectName("File_loc_box1")
        self.fileLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.File_loc_box1)
        self.File_loc_box2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.File_loc_box2.setObjectName("File_loc_box2")
        self.fileLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.File_loc_box2)
        self.gridLayout.addLayout(self.fileLayout, 0, 0, 1, 1)
        self.interfaceLayout = QtWidgets.QFormLayout()
        self.interfaceLayout.setObjectName("interfaceLayout")
        self.interfaceSelLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceSelLab.setObjectName("interfaceSelLab")
        self.interfaceLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.interfaceSelLab)
        self.interfaceUpdate = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.interfaceUpdate.setObjectName("interfaceUpdate")
        self.interfaceLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.interfaceUpdate)
        self.interfaceInput = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.interfaceInput.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceInput.setObjectName("interfaceInput")
        self.interfaceLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.interfaceInput)
        self.interfaceInputLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceInputLab.setObjectName("interfaceInputLab")
        self.interfaceLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.interfaceInputLab)
        self.interfaceOutput = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.interfaceOutput.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceOutput.setObjectName("interfaceOutput")
        self.interfaceLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.interfaceOutput)
        self.interfaceOutputLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceOutputLab.setObjectName("interfaceOutputLab")
        self.interfaceLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.interfaceOutputLab)
        self.gridLayout.addLayout(self.interfaceLayout, 1, 0, 1, 1)
        self.bitDepthLayout = QtWidgets.QGridLayout()
        self.bitDepthLayout.setObjectName("bitDepthLayout")
        self.bitDeptLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bitDeptLab.setObjectName("bitDeptLab")
        self.bitDepthLayout.addWidget(self.bitDeptLab, 0, 0, 1, 1)
        self.bitDepth = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.bitDepth.setMinimumSize(QtCore.QSize(162, 0))
        self.bitDepth.setObjectName("bitDepth")
        self.bitDepthLayout.addWidget(self.bitDepth, 1, 0, 1, 1)
        self.bitDeptDither = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.bitDeptDither.setObjectName("bitDeptDither")
        self.bitDepthLayout.addWidget(self.bitDeptDither, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.bitDepthLayout, 2, 0, 1, 1)
        self.fsLayout = QtWidgets.QGridLayout()
        self.fsLayout.setObjectName("fsLayout")
        self.fsSelLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fsSelLab.setObjectName("fsSelLab")
        self.fsLayout.addWidget(self.fsSelLab, 0, 0, 1, 1)
        self.fsStandard = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.fsStandard.setObjectName("fsStandard")
        self.fsLayout.addWidget(self.fsStandard, 0, 1, 3, 1)
        self.fsSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fsSel.setMinimumSize(QtCore.QSize(162, 0))
        self.fsSel.setObjectName("fsSel")
        self.fsLayout.addWidget(self.fsSel, 1, 0, 1, 1)
        self.fsEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fsEdit.setObjectName("fsEdit")
        self.fsLayout.addWidget(self.fsEdit, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.fsLayout, 3, 0, 1, 1)
        self.buffSize = QtWidgets.QVBoxLayout()
        self.buffSize.setObjectName("buffSize")
        self.buffSizeLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.buffSizeLab.setObjectName("buffSizeLab")
        self.buffSize.addWidget(self.buffSizeLab)
        self.buffSizeSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.buffSizeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.buffSizeSel.setObjectName("buffSizeSel")
        self.buffSize.addWidget(self.buffSizeSel)
        self.gridLayout.addLayout(self.buffSize, 4, 0, 1, 1)
        self.windowLayout = QtWidgets.QGridLayout()
        self.windowLayout.setObjectName("windowLayout")
        self.windowLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.windowLab.setObjectName("windowLab")
        self.windowLayout.addWidget(self.windowLab, 0, 0, 1, 1)
        self.OverlapTest = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.OverlapTest.setObjectName("OverlapTest")
        self.windowLayout.addWidget(self.OverlapTest, 0, 1, 1, 1)
        self.WindowSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.WindowSel.setMinimumSize(QtCore.QSize(162, 0))
        self.WindowSel.setObjectName("WindowSel")
        self.windowLayout.addWidget(self.WindowSel, 1, 0, 1, 1)
        self.overlapPercent = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.overlapPercent.setObjectName("overlapPercent")
        self.windowLayout.addWidget(self.overlapPercent, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.windowLayout, 5, 0, 1, 1)
        self.defFreqLayout = QtWidgets.QGridLayout()
        self.defFreqLayout.setObjectName("defFreqLayout")
        self.defFreqMinLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.defFreqMinLab.setObjectName("defFreqMinLab")
        self.defFreqLayout.addWidget(self.defFreqMinLab, 0, 0, 1, 1)
        self.defFreqMaxLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.defFreqMaxLab.setObjectName("defFreqMaxLab")
        self.defFreqLayout.addWidget(self.defFreqMaxLab, 0, 1, 1, 1)
        self.defFreqMinEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.defFreqMinEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMinEdit.setText("")
        self.defFreqMinEdit.setObjectName("defFreqMinEdit")
        self.defFreqLayout.addWidget(self.defFreqMinEdit, 1, 0, 1, 1)
        self.defFreqMaxEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.defFreqMaxEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMaxEdit.setObjectName("defFreqMaxEdit")
        self.defFreqLayout.addWidget(self.defFreqMaxEdit, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.defFreqLayout, 6, 0, 1, 1)
        self.styleSheet = QtWidgets.QVBoxLayout()
        self.styleSheet.setObjectName("styleSheet")
        self.styleSheetLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.styleSheetLab.setObjectName("styleSheetLab")
        self.styleSheet.addWidget(self.styleSheetLab)
        self.styleSheetSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.styleSheetSel.setMinimumSize(QtCore.QSize(162, 0))
        self.styleSheetSel.setObjectName("styleSheetSel")
        self.styleSheet.addWidget(self.styleSheetSel)
        self.gridLayout.addLayout(self.styleSheet, 7, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.comboBox_7 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_7.setMinimumSize(QtCore.QSize(162, 0))
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_7.addWidget(self.comboBox_7)
        self.gridLayout.addLayout(self.verticalLayout_7, 8, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.File_loc_box1, self.File_loc_box2)
        Dialog.setTabOrder(self.File_loc_box2, self.interfaceUpdate)
        Dialog.setTabOrder(self.interfaceUpdate, self.interfaceInput)
        Dialog.setTabOrder(self.interfaceInput, self.interfaceOutput)
        Dialog.setTabOrder(self.interfaceOutput, self.bitDepth)
        Dialog.setTabOrder(self.bitDepth, self.bitDeptDither)
        Dialog.setTabOrder(self.bitDeptDither, self.fsSel)
        Dialog.setTabOrder(self.fsSel, self.fsStandard)
        Dialog.setTabOrder(self.fsStandard, self.fsEdit)
        Dialog.setTabOrder(self.fsEdit, self.buffSizeSel)
        Dialog.setTabOrder(self.buffSizeSel, self.WindowSel)
        Dialog.setTabOrder(self.WindowSel, self.OverlapTest)
        Dialog.setTabOrder(self.OverlapTest, self.overlapPercent)
        Dialog.setTabOrder(self.overlapPercent, self.defFreqMinEdit)
        Dialog.setTabOrder(self.defFreqMinEdit, self.defFreqMaxEdit)
        Dialog.setTabOrder(self.defFreqMaxEdit, self.styleSheetSel)
        Dialog.setTabOrder(self.styleSheetSel, self.comboBox_7)
        Dialog.setTabOrder(self.comboBox_7, self.scrollArea)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.File_loc.setText(_translate("Dialog", "Default File Location"))
        self.interfaceSelLab.setText(_translate("Dialog", "select interface"))
        self.interfaceUpdate.setText(_translate("Dialog", "Update interface"))
        self.interfaceInputLab.setText(_translate("Dialog", "select Input"))
        self.interfaceOutputLab.setText(_translate("Dialog", "select Output"))
        self.bitDeptLab.setText(_translate("Dialog", "Bit Depth"))
        self.bitDeptDither.setText(_translate("Dialog", "dither on/off"))
        self.fsSelLab.setText(_translate("Dialog", "Select Fs"))
        self.fsStandard.setText(_translate("Dialog", "Standard Fs"))
        self.buffSizeLab.setText(_translate("Dialog", "buffersize"))
        self.windowLab.setText(_translate("Dialog", "Default Window"))
        self.OverlapTest.setText(_translate("Dialog", "Test"))
        self.defFreqMinLab.setText(_translate("Dialog", "default frequency Min"))
        self.defFreqMaxLab.setText(_translate("Dialog", "default frequency Max"))
        self.styleSheetLab.setText(_translate("Dialog", "Style Sheet"))
        self.label_8.setText(_translate("Dialog", "select interface"))

