# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae-Meas_Pref_0_1.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469, 644)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 400, 600))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(130, 10, 71, 16))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setGeometry(QtCore.QRect(0, 570, 400, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 410, 170, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.defFreqMaxLab = QtWidgets.QLabel(self.layoutWidget)
        self.defFreqMaxLab.setObjectName("defFreqMaxLab")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.defFreqMaxLab)
        self.defFreqMaxEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.defFreqMaxEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMaxEdit.setObjectName("defFreqMaxEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.defFreqMaxEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 190, 281, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.selFsLab = QtWidgets.QLabel(self.layoutWidget1)
        self.selFsLab.setObjectName("selFsLab")
        self.gridLayout.addWidget(self.selFsLab, 0, 0, 1, 1)
        self.standardFs = QtWidgets.QCheckBox(self.layoutWidget1)
        self.standardFs.setObjectName("standardFs")
        self.gridLayout.addWidget(self.standardFs, 0, 1, 3, 1)
        self.FsSel = QtWidgets.QComboBox(self.layoutWidget1)
        self.FsSel.setMinimumSize(QtCore.QSize(162, 0))
        self.FsSel.setObjectName("FsSel")
        self.gridLayout.addWidget(self.FsSel, 1, 0, 1, 1)
        self.fsEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.fsEdit.setObjectName("fsEdit")
        self.gridLayout.addWidget(self.fsEdit, 2, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 280, 170, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.buffSizeLab = QtWidgets.QLabel(self.layoutWidget2)
        self.buffSizeLab.setObjectName("buffSizeLab")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.buffSizeLab)
        self.buffSizeSel = QtWidgets.QComboBox(self.layoutWidget2)
        self.buffSizeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.buffSizeSel.setObjectName("buffSizeSel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.buffSizeSel)
        self.layoutWidget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 470, 170, 52))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_4.setMinimumSize(QtCore.QSize(162, 0))
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBox_4)
        self.layoutWidget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 350, 170, 52))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.defFreqMinLab = QtWidgets.QLabel(self.layoutWidget4)
        self.defFreqMinLab.setObjectName("defFreqMinLab")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.defFreqMinLab)
        self.defFreqMinEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.defFreqMinEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMinEdit.setObjectName("defFreqMinEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.defFreqMinEdit)
        self.layoutWidget5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 100, 296, 60))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.selInterfaceLab = QtWidgets.QLabel(self.layoutWidget5)
        self.selInterfaceLab.setObjectName("selInterfaceLab")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.selInterfaceLab)
        self.updateInterface = QtWidgets.QToolButton(self.layoutWidget5)
        self.updateInterface.setObjectName("updateInterface")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.updateInterface)
        self.interfaceSel = QtWidgets.QComboBox(self.layoutWidget5)
        self.interfaceSel.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceSel.setObjectName("interfaceSel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.interfaceSel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Opslag lokatie"))
        self.defFreqMaxLab.setText(_translate("Dialog", "default frequency Max"))
        self.selFsLab.setText(_translate("Dialog", "Select Fs"))
        self.standardFs.setText(_translate("Dialog", "Standard Fs"))
        self.buffSizeLab.setText(_translate("Dialog", "buffersize"))
        self.label_5.setText(_translate("Dialog", "select interface"))
        self.defFreqMinLab.setText(_translate("Dialog", "default frequency Min"))
        self.selInterfaceLab.setText(_translate("Dialog", "select interface"))
        self.updateInterface.setText(_translate("Dialog", "Update interface"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

