# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae-Meas_0_15.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MeasMain(object):
    def setupUi(self, MeasMain):
        MeasMain.setObjectName("MeasMain")
        MeasMain.resize(844, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MeasMain.sizePolicy().hasHeightForWidth())
        MeasMain.setSizePolicy(sizePolicy)
        MeasMain.setStyleSheet("font: 9pt \"SansSerif\";")
        self.measCentral = QtWidgets.QWidget(MeasMain)
        self.measCentral.setObjectName("measCentral")
        self.JbaeLogo = QtWidgets.QGraphicsView(self.measCentral)
        self.JbaeLogo.setGeometry(QtCore.QRect(10, 10, 240, 121))
        self.JbaeLogo.setMinimumSize(QtCore.QSize(240, 120))
        self.JbaeLogo.setMaximumSize(QtCore.QSize(16777215, 350))
        self.JbaeLogo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.JbaeLogo.setObjectName("JbaeLogo")
        self.testSig = QtWidgets.QToolButton(self.measCentral)
        self.testSig.setGeometry(QtCore.QRect(10, 520, 80, 23))
        self.testSig.setObjectName("testSig")
        self.startMeas = QtWidgets.QToolButton(self.measCentral)
        self.startMeas.setGeometry(QtCore.QRect(110, 520, 131, 23))
        self.startMeas.setObjectName("startMeas")
        self.tabWidget = QtWidgets.QTabWidget(self.measCentral)
        self.tabWidget.setGeometry(QtCore.QRect(10, 140, 241, 361))
        self.tabWidget.setMinimumSize(QtCore.QSize(240, 360))
        self.tabWidget.setObjectName("tabWidget")
        self.newTab = QtWidgets.QWidget()
        self.newTab.setObjectName("newTab")
        self.lineEdit = QtWidgets.QLineEdit(self.newTab)
        self.lineEdit.setGeometry(QtCore.QRect(0, 10, 231, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(self.newTab)
        self.widget.setGeometry(QtCore.QRect(1, 50, 231, 271))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sigTypeLab = QtWidgets.QLabel(self.widget)
        self.sigTypeLab.setObjectName("sigTypeLab")
        self.verticalLayout_3.addWidget(self.sigTypeLab)
        self.sigTypeSel = QtWidgets.QComboBox(self.widget)
        self.sigTypeSel.setMinimumSize(QtCore.QSize(140, 0))
        self.sigTypeSel.setStatusTip("")
        self.sigTypeSel.setObjectName("sigTypeSel")
        self.verticalLayout_3.addWidget(self.sigTypeSel)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.sigLevel = QtWidgets.QDial(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigLevel.sizePolicy().hasHeightForWidth())
        self.sigLevel.setSizePolicy(sizePolicy)
        self.sigLevel.setMinimumSize(QtCore.QSize(75, 75))
        self.sigLevel.setStatusTip("")
        self.sigLevel.setAccessibleDescription("")
        self.sigLevel.setObjectName("sigLevel")
        self.gridLayout_3.addWidget(self.sigLevel, 1, 1, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lengthLab = QtWidgets.QLabel(self.widget)
        self.lengthLab.setObjectName("lengthLab")
        self.verticalLayout_4.addWidget(self.lengthLab)
        self.lengthSelect = QtWidgets.QComboBox(self.widget)
        self.lengthSelect.setMinimumSize(QtCore.QSize(140, 0))
        self.lengthSelect.setObjectName("lengthSelect")
        self.verticalLayout_4.addWidget(self.lengthSelect)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sweepsLab = QtWidgets.QLabel(self.widget)
        self.sweepsLab.setObjectName("sweepsLab")
        self.verticalLayout_5.addWidget(self.sweepsLab)
        self.SweepsSelect = QtWidgets.QComboBox(self.widget)
        self.SweepsSelect.setMinimumSize(QtCore.QSize(140, 0))
        self.SweepsSelect.setAccessibleDescription("")
        self.SweepsSelect.setObjectName("SweepsSelect")
        self.verticalLayout_5.addWidget(self.SweepsSelect)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.startFreqLab = QtWidgets.QLabel(self.widget)
        self.startFreqLab.setObjectName("startFreqLab")
        self.gridLayout.addWidget(self.startFreqLab, 0, 0, 1, 1)
        self.startFreqSlid = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFreqSlid.sizePolicy().hasHeightForWidth())
        self.startFreqSlid.setSizePolicy(sizePolicy)
        self.startFreqSlid.setMinimumSize(QtCore.QSize(140, 0))
        self.startFreqSlid.setMaximum(100000)
        self.startFreqSlid.setOrientation(QtCore.Qt.Horizontal)
        self.startFreqSlid.setObjectName("startFreqSlid")
        self.gridLayout.addWidget(self.startFreqSlid, 1, 0, 1, 1)
        self.startFreqSpin = QtWidgets.QDoubleSpinBox(self.widget)
        self.startFreqSpin.setMinimumSize(QtCore.QSize(65, 0))
        self.startFreqSpin.setMaximum(100000.0)
        self.startFreqSpin.setProperty("value", 20.0)
        self.startFreqSpin.setObjectName("startFreqSpin")
        self.gridLayout.addWidget(self.startFreqSpin, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 4, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.endFreqLab = QtWidgets.QLabel(self.widget)
        self.endFreqLab.setObjectName("endFreqLab")
        self.gridLayout_2.addWidget(self.endFreqLab, 0, 0, 1, 1)
        self.endFreqSlid = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFreqSlid.sizePolicy().hasHeightForWidth())
        self.endFreqSlid.setSizePolicy(sizePolicy)
        self.endFreqSlid.setMinimumSize(QtCore.QSize(140, 0))
        self.endFreqSlid.setMaximum(100000)
        self.endFreqSlid.setOrientation(QtCore.Qt.Horizontal)
        self.endFreqSlid.setObjectName("endFreqSlid")
        self.gridLayout_2.addWidget(self.endFreqSlid, 1, 0, 1, 1)
        self.endFreqSpin = QtWidgets.QDoubleSpinBox(self.widget)
        self.endFreqSpin.setMinimumSize(QtCore.QSize(65, 0))
        self.endFreqSpin.setDecimals(0)
        self.endFreqSpin.setMaximum(100000.0)
        self.endFreqSpin.setProperty("value", 20000.0)
        self.endFreqSpin.setObjectName("endFreqSpin")
        self.gridLayout_2.addWidget(self.endFreqSpin, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 5, 0, 1, 2)
        self.lineEdit.raise_()
        self.tabWidget.addTab(self.newTab, "")
        self.LoadTab = QtWidgets.QWidget()
        self.LoadTab.setObjectName("LoadTab")
        self.pushButton = QtWidgets.QPushButton(self.LoadTab)
        self.pushButton.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.LoadTab)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 40, 211, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.LoadTab)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.recMeasurements = QtWidgets.QToolBox(self.LoadTab)
        self.recMeasurements.setGeometry(QtCore.QRect(10, 80, 211, 241))
        self.recMeasurements.setObjectName("recMeasurements")
        self.measurement = QtWidgets.QWidget()
        self.measurement.setGeometry(QtCore.QRect(0, 0, 211, 225))
        self.measurement.setObjectName("measurement")
        self.recMeasurements.addItem(self.measurement, "")
        self.measurement2 = QtWidgets.QWidget()
        self.measurement2.setGeometry(QtCore.QRect(0, 0, 211, 125))
        self.measurement2.setObjectName("measurement2")
        self.recMeasurements.addItem(self.measurement2, "")
        self.measurement3 = QtWidgets.QWidget()
        self.measurement3.setGeometry(QtCore.QRect(0, 0, 211, 21))
        self.measurement3.setObjectName("measurement3")
        self.recMeasurements.addItem(self.measurement3, "")
        self.measurement4 = QtWidgets.QWidget()
        self.measurement4.setGeometry(QtCore.QRect(0, 0, 211, 21))
        self.measurement4.setObjectName("measurement4")
        self.recMeasurements.addItem(self.measurement4, "")
        self.measurement5 = QtWidgets.QWidget()
        self.measurement5.setObjectName("measurement5")
        self.recMeasurements.addItem(self.measurement5, "")
        self.measurement6 = QtWidgets.QWidget()
        self.measurement6.setObjectName("measurement6")
        self.recMeasurements.addItem(self.measurement6, "")
        self.measurement7 = QtWidgets.QWidget()
        self.measurement7.setObjectName("measurement7")
        self.recMeasurements.addItem(self.measurement7, "")
        self.measurement8 = QtWidgets.QWidget()
        self.measurement8.setObjectName("measurement8")
        self.recMeasurements.addItem(self.measurement8, "")
        self.tabWidget.addTab(self.LoadTab, "")
        self.layoutWidget = QtWidgets.QWidget(self.measCentral)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 520, 481, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
#        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout.addWidget(self.dateTimeEdit)
        self.plotTop = QtWidgets.QGraphicsView(self.measCentral)
        self.plotTop.setGeometry(QtCore.QRect(260, 10, 521, 240))
        self.plotTop.setMinimumSize(QtCore.QSize(0, 240))
        self.plotTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotTop.setObjectName("plotTop")
        self.PlotBottom = QtWidgets.QGraphicsView(self.measCentral)
        self.PlotBottom.setGeometry(QtCore.QRect(260, 260, 521, 240))
        self.PlotBottom.setMinimumSize(QtCore.QSize(0, 240))
        self.PlotBottom.setObjectName("PlotBottom")
        self.layoutWidget1 = QtWidgets.QWidget(self.measCentral)
        self.layoutWidget1.setGeometry(QtCore.QRect(800, 10, 28, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.ViewPropTop = QtWidgets.QToolButton(self.layoutWidget1)
        self.ViewPropTop.setObjectName("ViewPropTop")
        self.verticalLayout.addWidget(self.ViewPropTop)
        self.zoomTop = QtWidgets.QToolButton(self.layoutWidget1)
        self.zoomTop.setObjectName("zoomTop")
        self.verticalLayout.addWidget(self.zoomTop)
        self.toolTop = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolTop.setObjectName("toolTop")
        self.verticalLayout.addWidget(self.toolTop)
        self.layoutWidget2 = QtWidgets.QWidget(self.measCentral)
        self.layoutWidget2.setGeometry(QtCore.QRect(800, 260, 28, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.ViewPropBBottom = QtWidgets.QToolButton(self.layoutWidget2)
        self.ViewPropBBottom.setObjectName("ViewPropBBottom")
        self.verticalLayout_2.addWidget(self.ViewPropBBottom)
        self.ZoomBottom = QtWidgets.QToolButton(self.layoutWidget2)
        self.ZoomBottom.setObjectName("ZoomBottom")
        self.verticalLayout_2.addWidget(self.ZoomBottom)
        self.toolBottom = QtWidgets.QToolButton(self.layoutWidget2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/WrenchSm.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolBottom.setIcon(icon)
        self.toolBottom.setObjectName("toolBottom")
        self.verticalLayout_2.addWidget(self.toolBottom)
        self.layoutWidget.raise_()
        self.JbaeLogo.raise_()
        self.testSig.raise_()
        self.startMeas.raise_()
        self.tabWidget.raise_()
        self.plotTop.raise_()
        self.layoutWidget.raise_()
        self.PlotBottom.raise_()
        self.layoutWidget.raise_()
        MeasMain.setCentralWidget(self.measCentral)
        self.menubar = QtWidgets.QMenuBar(MeasMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 23))
        self.menubar.setObjectName("menubar")
        self.menuJBae_Meas = QtWidgets.QMenu(self.menubar)
        self.menuJBae_Meas.setObjectName("menuJBae_Meas")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MeasMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MeasMain)
        self.statusbar.setObjectName("statusbar")
        MeasMain.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MeasMain)
        self.actionExit.setEnabled(True)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MeasMain)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_All = QtWidgets.QAction(MeasMain)
        self.actionSave_All.setObjectName("actionSave_All")
        self.actionPreferences = QtWidgets.QAction(MeasMain)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionSave_As = QtWidgets.QAction(MeasMain)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionDelete_Measurement = QtWidgets.QAction(MeasMain)
        self.actionDelete_Measurement.setObjectName("actionDelete_Measurement")
        self.actionOpen = QtWidgets.QAction(MeasMain)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MeasMain)
        self.actionNew.setObjectName("actionNew")
        self.menuJBae_Meas.addAction(self.actionNew)
        self.menuJBae_Meas.addAction(self.actionOpen)
        self.menuJBae_Meas.addAction(self.actionSave)
        self.menuJBae_Meas.addAction(self.actionSave_As)
        self.menuJBae_Meas.addAction(self.actionSave_All)
        self.menuJBae_Meas.addSeparator()
        self.menuJBae_Meas.addAction(self.actionPreferences)
        self.menuJBae_Meas.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionDelete_Measurement)
        self.menubar.addAction(self.menuJBae_Meas.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MeasMain)
        self.tabWidget.setCurrentIndex(0)
        self.recMeasurements.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MeasMain)
        MeasMain.setTabOrder(self.sigTypeSel, self.lengthSelect)
        MeasMain.setTabOrder(self.lengthSelect, self.SweepsSelect)
        MeasMain.setTabOrder(self.SweepsSelect, self.startFreqSlid)
        MeasMain.setTabOrder(self.startFreqSlid, self.startFreqSpin)
        MeasMain.setTabOrder(self.startFreqSpin, self.endFreqSlid)
        MeasMain.setTabOrder(self.endFreqSlid, self.endFreqSpin)
        MeasMain.setTabOrder(self.endFreqSpin, self.sigLevel)
        MeasMain.setTabOrder(self.sigLevel, self.startMeas)
        MeasMain.setTabOrder(self.startMeas, self.testSig)
        MeasMain.setTabOrder(self.testSig, self.ViewPropTop)
        MeasMain.setTabOrder(self.ViewPropTop, self.zoomTop)
        MeasMain.setTabOrder(self.zoomTop, self.toolTop)
        MeasMain.setTabOrder(self.toolTop, self.ViewPropBBottom)
        MeasMain.setTabOrder(self.ViewPropBBottom, self.ZoomBottom)
        MeasMain.setTabOrder(self.ZoomBottom, self.toolBottom)
        MeasMain.setTabOrder(self.toolBottom, self.tabWidget)
        MeasMain.setTabOrder(self.tabWidget, self.pushButton_2)
        MeasMain.setTabOrder(self.pushButton_2, self.pushButton)
        MeasMain.setTabOrder(self.pushButton, self.lineEdit_3)
        MeasMain.setTabOrder(self.lineEdit_3, self.plotTop)
        MeasMain.setTabOrder(self.plotTop, self.PlotBottom)
        MeasMain.setTabOrder(self.PlotBottom, self.dateTimeEdit)
        MeasMain.setTabOrder(self.dateTimeEdit, self.JbaeLogo)

    def retranslateUi(self, MeasMain):
        _translate = QtCore.QCoreApplication.translate
        MeasMain.setWindowTitle(_translate("MeasMain", "Meas"))
        self.testSig.setToolTip(_translate("MeasMain", "Open Menu Test Signal"))
        self.testSig.setText(_translate("MeasMain", "Test Signal"))
        self.startMeas.setToolTip(_translate("MeasMain", "Start Measurement"))
        self.startMeas.setText(_translate("MeasMain", "Start Measurement"))
        self.lineEdit.setText(_translate("MeasMain", "Meas Comment here"))
        self.sigTypeLab.setText(_translate("MeasMain", "Signal Type"))
        self.sigTypeSel.setToolTip(_translate("MeasMain", "Select Signal Type"))
        self.label.setText(_translate("MeasMain", "SoundLevel"))
        self.sigLevel.setToolTip(_translate("MeasMain", "Set Volume Level"))
        self.lengthLab.setText(_translate("MeasMain", "Length Signal"))
        self.lengthSelect.setToolTip(_translate("MeasMain", "Select Length of Signal in k samples"))
        self.sweepsLab.setText(_translate("MeasMain", "No Sweeps"))
        self.SweepsSelect.setToolTip(_translate("MeasMain", "Select number of itterations"))
        self.startFreqLab.setText(_translate("MeasMain", "Start Frequecy"))
        self.startFreqSlid.setToolTip(_translate("MeasMain", "Select Start Frequency"))
        self.startFreqSpin.setToolTip(_translate("MeasMain", "Set Start Frequency"))
        self.endFreqLab.setText(_translate("MeasMain", "End Frequency"))
        self.endFreqSlid.setToolTip(_translate("MeasMain", "Select End Frequency"))
        self.endFreqSpin.setToolTip(_translate("MeasMain", "Set End Frequency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.newTab), _translate("MeasMain", "Create New"))
        self.pushButton.setText(_translate("MeasMain", "PushButton"))
        self.pushButton_2.setText(_translate("MeasMain", "PushButton"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement), _translate("MeasMain", "Page 1"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement2), _translate("MeasMain", "Page 2"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement3), _translate("MeasMain", "Page 3"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement4), _translate("MeasMain", "Page 4"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement5), _translate("MeasMain", "Page 5"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement6), _translate("MeasMain", "Page 6"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement7), _translate("MeasMain", "Page 7"))
        self.recMeasurements.setItemText(self.recMeasurements.indexOf(self.measurement8), _translate("MeasMain", "Page 8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LoadTab), _translate("MeasMain", "Existing"))
        self.ViewPropTop.setText(_translate("MeasMain", "..."))
        self.zoomTop.setText(_translate("MeasMain", "..."))
        self.toolTop.setText(_translate("MeasMain", "..."))
        self.ViewPropBBottom.setText(_translate("MeasMain", "..."))
        self.ZoomBottom.setText(_translate("MeasMain", "..."))
        self.toolBottom.setText(_translate("MeasMain", "..."))
        self.menuJBae_Meas.setTitle(_translate("MeasMain", "File"))
        self.menuEdit.setTitle(_translate("MeasMain", "Edit"))
        self.actionExit.setText(_translate("MeasMain", "&Quite"))
        self.actionExit.setToolTip(_translate("MeasMain", "Exit Meas"))
        self.actionExit.setShortcut(_translate("MeasMain", "Ctrl+Q"))
        self.actionSave.setText(_translate("MeasMain", "&Save"))
        self.actionSave.setToolTip(_translate("MeasMain", "Save Measurements"))
        self.actionSave.setShortcut(_translate("MeasMain", "Ctrl+S"))
        self.actionSave_All.setText(_translate("MeasMain", "Save All"))
        self.actionSave_All.setToolTip(_translate("MeasMain", "Save All Measurements"))
        self.actionSave_All.setShortcut(_translate("MeasMain", "Ctrl+Shift+S"))
        self.actionPreferences.setText(_translate("MeasMain", "&Preferences"))
        self.actionPreferences.setToolTip(_translate("MeasMain", "Preferences Meas"))
        self.actionPreferences.setShortcut(_translate("MeasMain", "Ctrl+I"))
        self.actionSave_As.setText(_translate("MeasMain", "Save As"))
        self.actionSave_As.setToolTip(_translate("MeasMain", "Save Measurements As"))
        self.actionDelete_Measurement.setText(_translate("MeasMain", "Delete Measurement"))
        self.actionOpen.setText(_translate("MeasMain", "&Open"))
        self.actionNew.setText(_translate("MeasMain", "&New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MeasMain = QtWidgets.QMainWindow()
    ui = Ui_MeasMain()
    ui.setupUi(MeasMain)
    MeasMain.show()
    sys.exit(app.exec_())

