# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae_Meas_0_15_Pref.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(386, 500)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 668))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.fsSelLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fsSelLab.setObjectName("fsSelLab")
        self.gridLayout.addWidget(self.fsSelLab, 11, 0, 1, 1)
        self.interfaceInput = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.interfaceInput.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceInput.setObjectName("interfaceInput")
        self.gridLayout.addWidget(self.interfaceInput, 4, 0, 1, 1)
        self.interfaceOutputLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceOutputLab.setObjectName("interfaceOutputLab")
        self.gridLayout.addWidget(self.interfaceOutputLab, 5, 1, 1, 1)
        self.WindowSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.WindowSel.setMinimumSize(QtCore.QSize(162, 0))
        self.WindowSel.setObjectName("WindowSel")
        self.gridLayout.addWidget(self.WindowSel, 18, 0, 1, 1)
        self.interfaceSelLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceSelLab.setObjectName("interfaceSelLab")
        self.gridLayout.addWidget(self.interfaceSelLab, 3, 0, 1, 1)
        self.defFreqMaxEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.defFreqMaxEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMaxEdit.setObjectName("defFreqMaxEdit")
        self.gridLayout.addWidget(self.defFreqMaxEdit, 20, 1, 1, 1)
        self.buffSizeLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.buffSizeLab.setObjectName("buffSizeLab")
        self.gridLayout.addWidget(self.buffSizeLab, 14, 0, 1, 1)
        self.defFreqMaxLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.defFreqMaxLab.setObjectName("defFreqMaxLab")
        self.gridLayout.addWidget(self.defFreqMaxLab, 19, 1, 1, 1)
        self.buffSizeSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.buffSizeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.buffSizeSel.setObjectName("buffSizeSel")
        self.gridLayout.addWidget(self.buffSizeSel, 15, 0, 1, 1)
        self.bitDeptLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bitDeptLab.setObjectName("bitDeptLab")
        self.gridLayout.addWidget(self.bitDeptLab, 9, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 2)
        self.styleSheetLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.styleSheetLab.setObjectName("styleSheetLab")
        self.gridLayout.addWidget(self.styleSheetLab, 22, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 21, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.File_loc_box1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.File_loc_box1.setObjectName("File_loc_box1")
        self.horizontalLayout_3.addWidget(self.File_loc_box1)
        self.File_loc_but = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.File_loc_but.setMinimumSize(QtCore.QSize(16, 16))
        self.File_loc_but.setMaximumSize(QtCore.QSize(64, 64))
        self.File_loc_but.setObjectName("File_loc_but")
        self.horizontalLayout_3.addWidget(self.File_loc_but)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.interfaceUpdate = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.interfaceUpdate.setObjectName("interfaceUpdate")
        self.gridLayout.addWidget(self.interfaceUpdate, 3, 1, 1, 1)
        self.bitDepth = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.bitDepth.setMinimumSize(QtCore.QSize(162, 0))
        self.bitDepth.setObjectName("bitDepth")
        self.gridLayout.addWidget(self.bitDepth, 10, 0, 1, 1)
        self.interfaceInputLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceInputLab.setObjectName("interfaceInputLab")
        self.gridLayout.addWidget(self.interfaceInputLab, 4, 1, 1, 1)
        self.fsStandard = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.fsStandard.setObjectName("fsStandard")
        self.gridLayout.addWidget(self.fsStandard, 12, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_7.setMinimumSize(QtCore.QSize(162, 0))
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout.addWidget(self.comboBox_7, 25, 0, 1, 1)
        self.fsEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fsEdit.setObjectName("fsEdit")
        self.gridLayout.addWidget(self.fsEdit, 13, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 24, 0, 1, 1)
        self.OverlapTest = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.OverlapTest.setObjectName("OverlapTest")
        self.gridLayout.addWidget(self.OverlapTest, 17, 1, 1, 1)
        self.interfaceOutputLab_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.interfaceOutputLab_2.setObjectName("interfaceOutputLab_2")
        self.gridLayout.addWidget(self.interfaceOutputLab_2, 7, 1, 1, 1)
        self.styleSheetSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.styleSheetSel.setMinimumSize(QtCore.QSize(162, 0))
        self.styleSheetSel.setObjectName("styleSheetSel")
        self.gridLayout.addWidget(self.styleSheetSel, 23, 0, 1, 1)
        self.interfaceOutput = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.interfaceOutput.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceOutput.setObjectName("interfaceOutput")
        self.gridLayout.addWidget(self.interfaceOutput, 5, 0, 1, 1)
        self.defFreqMinLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.defFreqMinLab.setObjectName("defFreqMinLab")
        self.gridLayout.addWidget(self.defFreqMinLab, 19, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 16, 0, 1, 2)
        self.bitDeptDither = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.bitDeptDither.setObjectName("bitDeptDither")
        self.gridLayout.addWidget(self.bitDeptDither, 10, 1, 1, 1)
        self.windowLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.windowLab.setObjectName("windowLab")
        self.gridLayout.addWidget(self.windowLab, 17, 0, 1, 1)
        self.interfaceOutput_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.interfaceOutput_2.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceOutput_2.setObjectName("interfaceOutput_2")
        self.gridLayout.addWidget(self.interfaceOutput_2, 7, 0, 1, 1)
        self.overlapPercent = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.overlapPercent.setObjectName("overlapPercent")
        self.gridLayout.addWidget(self.overlapPercent, 18, 1, 1, 1)
        self.defFreqMinEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.defFreqMinEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMinEdit.setText("")
        self.defFreqMinEdit.setObjectName("defFreqMinEdit")
        self.gridLayout.addWidget(self.defFreqMinEdit, 20, 0, 1, 1)
        self.fsSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fsSel.setMinimumSize(QtCore.QSize(162, 0))
        self.fsSel.setObjectName("fsSel")
        self.gridLayout.addWidget(self.fsSel, 12, 0, 1, 1)
        self.File_loc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.File_loc.setObjectName("File_loc")
        self.gridLayout.addWidget(self.File_loc, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.File_loc_box1, self.interfaceUpdate)
        Dialog.setTabOrder(self.interfaceUpdate, self.interfaceInput)
        Dialog.setTabOrder(self.interfaceInput, self.interfaceOutput)
        Dialog.setTabOrder(self.interfaceOutput, self.bitDepth)
        Dialog.setTabOrder(self.bitDepth, self.bitDeptDither)
        Dialog.setTabOrder(self.bitDeptDither, self.fsSel)
        Dialog.setTabOrder(self.fsSel, self.fsStandard)
        Dialog.setTabOrder(self.fsStandard, self.fsEdit)
        Dialog.setTabOrder(self.fsEdit, self.buffSizeSel)
        Dialog.setTabOrder(self.buffSizeSel, self.WindowSel)
        Dialog.setTabOrder(self.WindowSel, self.OverlapTest)
        Dialog.setTabOrder(self.OverlapTest, self.overlapPercent)
        Dialog.setTabOrder(self.overlapPercent, self.defFreqMinEdit)
        Dialog.setTabOrder(self.defFreqMinEdit, self.defFreqMaxEdit)
        Dialog.setTabOrder(self.defFreqMaxEdit, self.styleSheetSel)
        Dialog.setTabOrder(self.styleSheetSel, self.comboBox_7)
        Dialog.setTabOrder(self.comboBox_7, self.scrollArea)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fsSelLab.setText(_translate("Dialog", "Select Fs"))
        self.interfaceOutputLab.setText(_translate("Dialog", "select Output"))
        self.interfaceSelLab.setText(_translate("Dialog", "select interface"))
        self.buffSizeLab.setText(_translate("Dialog", "buffersize"))
        self.defFreqMaxLab.setText(_translate("Dialog", "default frequency Max"))
        self.bitDeptLab.setText(_translate("Dialog", "Bit Depth"))
        self.styleSheetLab.setText(_translate("Dialog", "Style Sheet"))
        self.File_loc_but.setText(_translate("Dialog", "Map"))
        self.interfaceUpdate.setText(_translate("Dialog", "Update interface"))
        self.interfaceInputLab.setText(_translate("Dialog", "select Input"))
        self.fsStandard.setText(_translate("Dialog", "Standard Fs"))
        self.label_8.setText(_translate("Dialog", "select interface"))
        self.OverlapTest.setText(_translate("Dialog", "Test"))
        self.interfaceOutputLab_2.setText(_translate("Dialog", "Channels"))
        self.defFreqMinLab.setText(_translate("Dialog", "default frequency Min"))
        self.bitDeptDither.setText(_translate("Dialog", "dither on/off"))
        self.windowLab.setText(_translate("Dialog", "Default Window"))
        self.File_loc.setText(_translate("Dialog", "Default File Location"))

