# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae-Meas_Fig_0_1.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets  # , QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 447)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 410, 394))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.titleLab.setObjectName("titleLab")
        self.titleLayout.addWidget(self.titleLab)
        self.titleEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.titleEdit.setMinimumSize(QtCore.QSize(240, 0))
        self.titleEdit.setObjectName("titleEdit")
        self.titleLayout.addWidget(self.titleEdit)
        self.gridLayout_2.addLayout(self.titleLayout, 0, 0, 1, 4)
        self.plotTypeLayout = QtWidgets.QVBoxLayout()
        self.plotTypeLayout.setObjectName("plotTypeLayout")
        self.plotTypeLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.plotTypeLab.setObjectName("plotTypeLab")
        self.plotTypeLayout.addWidget(self.plotTypeLab)
        self.plotTypeSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.plotTypeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.plotTypeSel.setObjectName("plotTypeSel")
        self.plotTypeLayout.addWidget(self.plotTypeSel)
        self.gridLayout_2.addLayout(self.plotTypeLayout, 1, 0, 1, 2)
        self.xUnitLayout = QtWidgets.QVBoxLayout()
        self.xUnitLayout.setObjectName("xUnitLayout")
        self.xUnitLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.xUnitLab.setObjectName("xUnitLab")
        self.xUnitLayout.addWidget(self.xUnitLab)
        self.xUnitSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.xUnitSel.setMinimumSize(QtCore.QSize(162, 0))
        self.xUnitSel.setObjectName("xUnitSel")
        self.xUnitLayout.addWidget(self.xUnitSel)
        self.gridLayout_2.addLayout(self.xUnitLayout, 3, 0, 1, 2)
        self.yUnitLayout = QtWidgets.QVBoxLayout()
        self.yUnitLayout.setObjectName("yUnitLayout")
        self.yUnitLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.yUnitLab.setObjectName("yUnitLab")
        self.yUnitLayout.addWidget(self.yUnitLab)
        self.yUnitSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.yUnitSel.setMinimumSize(QtCore.QSize(162, 0))
        self.yUnitSel.setObjectName("yUnitSel")
        self.yUnitLayout.addWidget(self.yUnitSel)
        self.gridLayout_2.addLayout(self.yUnitLayout, 3, 2, 1, 2)
        self.smoothingLayout = QtWidgets.QVBoxLayout()
        self.smoothingLayout.setObjectName("smoothingLayout")
        self.smoothingLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.smoothingLab.setObjectName("smoothingLab")
        self.smoothingLayout.addWidget(self.smoothingLab)
        self.smoothingSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.smoothingSel.setMinimumSize(QtCore.QSize(162, 0))
        self.smoothingSel.setObjectName("smoothingSel")
        self.smoothingLayout.addWidget(self.smoothingSel)
        self.gridLayout_2.addLayout(self.smoothingLayout, 4, 0, 1, 2)
        self.phaseCheck_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.phaseCheck_4.setObjectName("phaseCheck_4")
        self.gridLayout_2.addWidget(self.phaseCheck_4, 6, 0, 1, 2)
        self.phaseCheck_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.phaseCheck_3.setObjectName("phaseCheck_3")
        self.gridLayout_2.addWidget(self.phaseCheck_3, 7, 3, 1, 1)
        self.specTypeLayout = QtWidgets.QVBoxLayout()
        self.specTypeLayout.setObjectName("specTypeLayout")
        self.specTypeLab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.specTypeLab.setObjectName("specTypeLab")
        self.specTypeLayout.addWidget(self.specTypeLab)
        self.specTypeSel = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.specTypeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.specTypeSel.setObjectName("specTypeSel")
        self.specTypeLayout.addWidget(self.specTypeSel)
        self.gridLayout_2.addLayout(self.specTypeLayout, 2, 0, 1, 2)
        self.weightingCheck = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.weightingCheck.setObjectName("weightingCheck")
        self.gridLayout_2.addWidget(self.weightingCheck, 5, 0, 1, 2)
        self.phaseCheck = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.phaseCheck.setObjectName("phaseCheck")
        self.gridLayout_2.addWidget(self.phaseCheck, 6, 3, 1, 1)
        self.phaseCheck_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.phaseCheck_2.setObjectName("phaseCheck_2")
        self.gridLayout_2.addWidget(self.phaseCheck_2, 7, 0, 1, 2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLab.setText(_translate("Dialog", "Title Adition"))
        self.plotTypeLab.setText(_translate("Dialog", "Plot Type"))
        self.xUnitLab.setText(_translate("Dialog", "Unit X-label"))
        self.yUnitLab.setText(_translate("Dialog", "Unit Y-label"))
        self.smoothingLab.setText(_translate("Dialog", "Smoothing"))
        self.phaseCheck_4.setText(_translate("Dialog", "Mag - Phase/ Real - Imag"))
        self.phaseCheck_3.setText(_translate("Dialog", "Lin/ Log spectrum"))
        self.specTypeLab.setText(_translate("Dialog", "Spectrum Type"))
        self.weightingCheck.setText(_translate("Dialog", "Weighting"))
        self.phaseCheck.setText(_translate("Dialog", "Phase Wrap"))
        self.phaseCheck_2.setText(_translate("Dialog", "Full/ Half Spectrum"))

