# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jBae-Meas_Pref_0_15.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 741)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 420, 688))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.File_loc_box1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.File_loc_box1.setGeometry(QtCore.QRect(30, 30, 113, 20))
        self.File_loc_box1.setObjectName("File_loc_box1")
        self.File_loc_box2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.File_loc_box2.setGeometry(QtCore.QRect(160, 30, 113, 20))
        self.File_loc_box2.setObjectName("File_loc_box2")
        self.File_loc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.File_loc.setGeometry(QtCore.QRect(30, 10, 141, 16))
        self.File_loc.setObjectName("File_loc")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 200, 281, 85))
        self.layoutWidget.setObjectName("layoutWidget")
        self.fsLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.fsLayout.setObjectName("fsLayout")
        self.fsSelLab = QtWidgets.QLabel(self.layoutWidget)
        self.fsSelLab.setObjectName("fsSelLab")
        self.fsLayout.addWidget(self.fsSelLab, 0, 0, 1, 1)
        self.fsStandard = QtWidgets.QCheckBox(self.layoutWidget)
        self.fsStandard.setObjectName("fsStandard")
        self.fsLayout.addWidget(self.fsStandard, 0, 1, 3, 1)
        self.fsSel = QtWidgets.QComboBox(self.layoutWidget)
        self.fsSel.setMinimumSize(QtCore.QSize(162, 0))
        self.fsSel.setObjectName("fsSel")
        self.fsLayout.addWidget(self.fsSel, 1, 0, 1, 1)
        self.fsEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fsEdit.setObjectName("fsEdit")
        self.fsLayout.addWidget(self.fsEdit, 2, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 350, 191, 52))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.windowLab = QtWidgets.QLabel(self.layoutWidget_2)
        self.windowLab.setObjectName("windowLab")
        self.verticalLayout_5.addWidget(self.windowLab)
        self.WindowSel = QtWidgets.QComboBox(self.layoutWidget_2)
        self.WindowSel.setMinimumSize(QtCore.QSize(162, 0))
        self.WindowSel.setObjectName("WindowSel")
        self.verticalLayout_5.addWidget(self.WindowSel)
        self.bitDeptDither = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.bitDeptDither.setGeometry(QtCore.QRect(220, 170, 101, 17))
        self.bitDeptDither.setObjectName("bitDeptDither")
        self.layoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 150, 191, 52))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bitDeptLab = QtWidgets.QLabel(self.layoutWidget_3)
        self.bitDeptLab.setObjectName("bitDeptLab")
        self.verticalLayout_6.addWidget(self.bitDeptLab)
        self.bitDepth = QtWidgets.QComboBox(self.layoutWidget_3)
        self.bitDepth.setMinimumSize(QtCore.QSize(162, 0))
        self.bitDepth.setObjectName("bitDepth")
        self.verticalLayout_6.addWidget(self.bitDepth)
        self.overlapPercent = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.overlapPercent.setGeometry(QtCore.QRect(230, 370, 62, 22))
        self.overlapPercent.setObjectName("overlapPercent")
        self.OverlapTest = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.OverlapTest.setGeometry(QtCore.QRect(230, 340, 91, 23))
        self.OverlapTest.setObjectName("OverlapTest")
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 520, 191, 52))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.styleSheet = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.styleSheet.setObjectName("styleSheet")
        self.styleSheetLab = QtWidgets.QLabel(self.layoutWidget1)
        self.styleSheetLab.setObjectName("styleSheetLab")
        self.styleSheet.addWidget(self.styleSheetLab)
        self.styleSheetSel = QtWidgets.QComboBox(self.layoutWidget1)
        self.styleSheetSel.setMinimumSize(QtCore.QSize(162, 0))
        self.styleSheetSel.setObjectName("styleSheetSel")
        self.styleSheet.addWidget(self.styleSheetSel)
        self.layoutWidget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget2.setGeometry(QtCore.QRect(219, 459, 191, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.defFreqMax = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.defFreqMax.setObjectName("defFreqMax")
        self.defFreqMaxLab = QtWidgets.QLabel(self.layoutWidget2)
        self.defFreqMaxLab.setObjectName("defFreqMaxLab")
        self.defFreqMax.addWidget(self.defFreqMaxLab)
        self.defFreqMaxEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.defFreqMaxEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMaxEdit.setObjectName("defFreqMaxEdit")
        self.defFreqMax.addWidget(self.defFreqMaxEdit)
        self.layoutWidget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 460, 191, 52))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.defFreqMin = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.defFreqMin.setObjectName("defFreqMin")
        self.defFreqMinLab = QtWidgets.QLabel(self.layoutWidget3)
        self.defFreqMinLab.setObjectName("defFreqMinLab")
        self.defFreqMin.addWidget(self.defFreqMinLab)
        self.defFreqMinEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.defFreqMinEdit.setMinimumSize(QtCore.QSize(162, 0))
        self.defFreqMinEdit.setObjectName("defFreqMinEdit")
        self.defFreqMin.addWidget(self.defFreqMinEdit)
        self.layoutWidget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 290, 191, 52))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.buffSize = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.buffSize.setObjectName("buffSize")
        self.buffSizeLab = QtWidgets.QLabel(self.layoutWidget4)
        self.buffSizeLab.setObjectName("buffSizeLab")
        self.buffSize.addWidget(self.buffSizeLab)
        self.buffSizeSel = QtWidgets.QComboBox(self.layoutWidget4)
        self.buffSizeSel.setMinimumSize(QtCore.QSize(162, 0))
        self.buffSizeSel.setObjectName("buffSizeSel")
        self.buffSize.addWidget(self.buffSizeSel)
        self.layoutWidget5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 61, 295, 93))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.interfaceLayout = QtWidgets.QFormLayout(self.layoutWidget5)
        self.interfaceLayout.setObjectName("interfaceLayout")
        self.interfaceSelLab = QtWidgets.QLabel(self.layoutWidget5)
        self.interfaceSelLab.setObjectName("interfaceSelLab")
        self.interfaceLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.interfaceSelLab)
        self.interfaceUpdate = QtWidgets.QToolButton(self.layoutWidget5)
        self.interfaceUpdate.setObjectName("interfaceUpdate")
        self.interfaceLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.interfaceUpdate)
        self.interfaceInput = QtWidgets.QComboBox(self.layoutWidget5)
        self.interfaceInput.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceInput.setObjectName("interfaceInput")
        self.interfaceLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.interfaceInput)
        self.interfaceInputLab = QtWidgets.QLabel(self.layoutWidget5)
        self.interfaceInputLab.setObjectName("interfaceInputLab")
        self.interfaceLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.interfaceInputLab)
        self.interfaceOutput = QtWidgets.QComboBox(self.layoutWidget5)
        self.interfaceOutput.setMinimumSize(QtCore.QSize(162, 0))
        self.interfaceOutput.setObjectName("interfaceOutput")
        self.interfaceLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.interfaceOutput)
        self.interfaceOutputLab = QtWidgets.QLabel(self.layoutWidget5)
        self.interfaceOutputLab.setObjectName("interfaceOutputLab")
        self.interfaceLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.interfaceOutputLab)
        self.layoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 610, 191, 52))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_7.setMinimumSize(QtCore.QSize(162, 0))
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_7.addWidget(self.comboBox_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.File_loc_box1, self.File_loc_box2)
        Dialog.setTabOrder(self.File_loc_box2, self.interfaceUpdate)
        Dialog.setTabOrder(self.interfaceUpdate, self.interfaceInput)
        Dialog.setTabOrder(self.interfaceInput, self.interfaceOutput)
        Dialog.setTabOrder(self.interfaceOutput, self.bitDepth)
        Dialog.setTabOrder(self.bitDepth, self.bitDeptDither)
        Dialog.setTabOrder(self.bitDeptDither, self.fsSel)
        Dialog.setTabOrder(self.fsSel, self.fsStandard)
        Dialog.setTabOrder(self.fsStandard, self.fsEdit)
        Dialog.setTabOrder(self.fsEdit, self.buffSizeSel)
        Dialog.setTabOrder(self.buffSizeSel, self.WindowSel)
        Dialog.setTabOrder(self.WindowSel, self.OverlapTest)
        Dialog.setTabOrder(self.OverlapTest, self.overlapPercent)
        Dialog.setTabOrder(self.overlapPercent, self.defFreqMinEdit)
        Dialog.setTabOrder(self.defFreqMinEdit, self.defFreqMaxEdit)
        Dialog.setTabOrder(self.defFreqMaxEdit, self.styleSheetSel)
        Dialog.setTabOrder(self.styleSheetSel, self.comboBox_7)
        Dialog.setTabOrder(self.comboBox_7, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.scrollArea)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.File_loc.setText(_translate("Dialog", "Default File Location"))
        self.fsSelLab.setText(_translate("Dialog", "Select Fs"))
        self.fsStandard.setText(_translate("Dialog", "Standard Fs"))
        self.windowLab.setText(_translate("Dialog", "Default Window"))
        self.bitDeptDither.setText(_translate("Dialog", "dither on/off"))
        self.bitDeptLab.setText(_translate("Dialog", "Bit Depth"))
        self.OverlapTest.setText(_translate("Dialog", "Test"))
        self.styleSheetLab.setText(_translate("Dialog", "Style Sheet"))
        self.defFreqMaxLab.setText(_translate("Dialog", "default frequency Max"))
        self.defFreqMinLab.setText(_translate("Dialog", "default frequency Min"))
        self.defFreqMinEdit.setText(_translate("Dialog", "20"))
        self.buffSizeLab.setText(_translate("Dialog", "buffersize"))
        self.interfaceSelLab.setText(_translate("Dialog", "select interface"))
        self.interfaceUpdate.setText(_translate("Dialog", "Update interface"))
        self.interfaceInputLab.setText(_translate("Dialog", "select Input"))
        self.interfaceOutputLab.setText(_translate("Dialog", "select Output"))
        self.label_8.setText(_translate("Dialog", "select interface"))

